datadir:
  ../eulernjf_data/dance/test_1/
  #../eulernjf_data/subject_50027_jump/train/
  #../eulernjf_data/subject_50002_50027_run/train/
bodymodel: "../body_models/"
training:
  batch: 1 
  epochs: 200
  lr: 1e-3
  expt: "njfode"
  code_size: 16 
  encoding: "joints"
  aug_dim: 0
data:
  seq_length: 32 
  max_frames: 1000
  feature_dir: ../eulernjf_data/wks/
weight:
  directory : "../models_njf/dancing/"
  path: "../models_njf/dancing/njf_dance"
logging:
  directory : "../logs/njf_dancing/"
  #directory : "../logs/50002_posing_jj_pointfeat/"
test:
  test: True 
  datadir:
    ../eulernjf_data/dance/train_1/
    #../eulernjf_data/subject_50027_run/train/
  dataset_meshdir:
    ../eulernjf_data/first_frames/
  motion_name:
    "jumping_jacks"
  mode:
    "nonhuman"
  nonhuman_mesh:
    #../eulernjf_data/nonhuman/bunny/bunny.ply 
    #../eulernjf_data/nonhuman/jared/jared_v1.ply 
    ../eulernjf_data/nonhuman/skeletonzombie/skeletonzombie_t_rot90.ply 
    #../eulernjf_data/nonhuman/maynard/maynard_t.ply 
    #../eulernjf_data/nonhuman/mousey/mousey_t.ply 
    #../eulernjf_data/nonhuman/holey/holey_man.ply 
    #../eulernjf_data/nonhuman/horse/horse.ply 
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.ply 
    #../eulernjf_data/nonhuman/prisoner/prisoner_t.ply 
  nonhuman_features:
    #../eulernjf_data/nonhuman/bunny/bunny.npy
    #../eulernjf_data/nonhuman/jared/jared_v1.npy
    ../eulernjf_data/nonhuman/skeletonzombie/skeletonzombie_t_rot90.npy
    #../eulernjf_data/nonhuman/maynard/maynard_t.npy
    #../eulernjf_data/nonhuman/mousey/mousey_t.npy
    #../eulernjf_data/nonhuman/holey/holey_man.npy
    #../eulernjf_data/nonhuman/horse/horse.npy
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.npy
    #../eulernjf_data/nonhuman/prisoner/prisoner_t.npy
  objroot: ../eulernjf_data/running_on_spot_dino/
  src_names: ["Fanie"]
  tgt_names: ["Theodora"] #"50021"] #"50004"]
  result_dir: "../Siggraph_Asia/dancing/unseen/"
  stepsize: 0.05
  method: "njf"