datadir:
  ../eulernjf_data/jumping_jacks/train_3/
  #../eulernjf_data/subject_50027_jump/train/
  #../eulernjf_data/subject_50002_50027_jump/train/
bodymodel: "../body_models/"
training:
  batch: 1 
  epochs: 2000
  lr: 1e-4
  expt: "njfode"
  code_size: 16 
  encoding: "joints"
data:
  seq_length: 32 
  max_frames: 10000
weight:
  directory : "../models/"
  path: "../models/posing_jj_pointfeat_all_dmpl"
logging:
  directory : "../logs/posing_jj_pointfeat_all_dmpl/"
  #directory : "../logs/50002_posing_jj_pointfeat/"
test:
  test: False 
  datadir:
    ../eulernjf_data/subject_50002_run/train/
  dataset_meshdir:
    ../eulernjf_data/first_frames/
  motion_name:
    "jumping_jacks"
  mode:
    "nonhuman"
  nonhuman_mesh:
    #../eulernjf_data/nonhuman/bunny/bunny.ply 
    ../eulernjf_data/nonhuman/jared/jared_v1.ply 
    #../eulernjf_data/nonhuman/horse/horse.ply 
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.ply 
  nonhuman_features:
    #../eulernjf_data/nonhuman/bunny/bunny.npy
    ../eulernjf_data/nonhuman/jared/jared_v1.npy
    #../eulernjf_data/nonhuman/horse/horse.npy
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.npy
  objroot: ../eulernjf_data/running_on_spot_dino/
  src_names: ["50027"]
  tgt_names: ["50002"] #"50021"] #"50004"]
  result_dir: "../sig24_results/posing/"
  stepsize: 0.05
  method: "eulernjf"