datadir:
  ../eulernjf_data/punching/test_3/
  #../eulernjf_data/subject_50027_jump/train/
  #../eulernjf_data/subject_50002_50027_run/train/
bodymodel: "../body_models/"
training:
  batch: 1 
  epochs: 150
  lr: 1e-3
  expt: "njfode"
  code_size: 16 
  encoding: "joints"
  aug_dim: 0
data:
  seq_length: 32 
  max_frames: 10000
  feature_dir: ../eulernjf_data/wks/
weight:
  directory : "../models_njf/punching/"
  path: "../models_njf/punching/punching_njf"
logging:
  directory : "../logs/njf_punching/"
  #directory : "../logs/50002_posing_jj_pointfeat/"
test:
  test: True 
  datadir:
    ../eulernjf_data/punching/train_7/
    #../eulernjf_data/subject_50027_run/train/
  dataset_meshdir:
    ../eulernjf_data/first_frames/
  motion_name:
    "punching"
  mode:
    "human"
  nonhuman_mesh:
    #../eulernjf_data/nonhuman/bunny/bunny_rot90.ply 
    ../eulernjf_data/nonhuman/faust/scan_rot90.ply 
    #../eulernjf_data/nonhuman/maynard/maynard_rot90.ply 
    #../eulernjf_data/nonhuman/jared/jared_v1.ply 
    #../eulernjf_data/nonhuman/holey/holey_man.ply 
    #../eulernjf_data/nonhuman/horse/horse.ply 
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.ply 
  nonhuman_features:
    #../eulernjf_data/nonhuman/bunny/bunny_rot90.npy
    ../eulernjf_data/nonhuman/faust/scan_rot90.npy
    #../eulernjf_data/nonhuman/maynard/maynard_rot90.npy
    #../eulernjf_data/nonhuman/jared/jared_v1.npy
    #../eulernjf_data/nonhuman/holey/holey_man.npy
    #../eulernjf_data/nonhuman/horse/horse.npy
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.npy
  objroot: ../eulernjf_data/running_on_spot_dino/
  src_names: ["50027","50007"]
  tgt_names: ["50002"] #"50004","50009","50020","50021","50027"] #"50021"] #"50004"]
  result_dir: "../Siggraph_Asia/punching/unseen/"
  stepsize: 0.05
  method: "njf"