datadir:
  ../eulernjf_data/subject_50002_50027_jump/train/
  #../eulernjf_data/jumping_jacks/train/
  #../eulernjf_data/subject_50002_jump/train/
bodymodel: "../body_models/"
training:
  batch: 1 
  epochs: 2000
  lr: 1e-3
  expt: "njfode"
  code_size: 16 
  encoding: "joints"
data:
  seq_length: 32 
  max_frames: 10000
weight:
  directory : "../models/"
  path: "../models/Vode_jj_pointfeat"
  pose: "../models/posing_jj_pointfeat_2pairs"
logging:
  #directory : "../logs/secondary_jj_wo_primattn_eval/"
  #directory : "../logs/secondary_jj_pointfeat_simul/"
  #directory : "../logs/secondary_jj_pointfeat/"
  directory : "../logs/Vsecondary_jj_pointfeat/"
test:
  test: True 
  datadir:
    ../eulernjf_data/subject_50002_jump/train/
  objroot: ../eulernjf_data/running_on_spot_dino/
  src_names: ["50027"] #"50027"] #"50004","50007","50009","50022","50026","50027"]
  tgt_names: ["50002"] #"50021"] #"50004"]
  result_dir: "../sig24_results/jumping_jacks_vode/"
  stepsize: 0.05
  method: "eulernjf"