datadir:
  ../eulernjf_data/d4d/train/
bodymodel: "../body_models/"
training:
  batch: 1 
  epochs: 2000
  lr: 1e-4
  expt: "njfode"
  code_size: 16 
  encoding: "joints"
data:
  seq_length: 32 
  max_frames: 10000
  feature_dir: ../eulernjf_data/wks/
weight:
  directory : "../models/"
  #path: "../models/ode_d4d_pointfeat_wks_split_1_b0_wbeta"
  path: "../models/ode_d4d_pointfeat_wks_split_1_b01_wbeta"
  pose: "../models/posing_jj_pointfeat_all_dmpl" 
logging:
  directory : "../logs/secondary_d4d_pointfeat_wks_split_1/"
test:
  test: True 
  datadir:
    ../eulernjf_data/d4d/train/
  dataset_meshdir:
    ../eulernjf_data/first_frames/
  motion_name:
    "jumping_jacks"
  mode:
    "nonhuman"
  nonhuman_mesh:
    #../eulernjf_data/nonhuman/wolf/wolf_d4d_dog.ply 
    #../eulernjf_data/nonhuman/wolf/wolf_d4d_deer.ply 
    #../eulernjf_data/nonhuman/wolf/wolf_bear.ply 
    #../eulernjf_data/nonhuman/triceratop/triceratop.ply 
    #../eulernjf_data/nonhuman/triceratop/triceratop_bear.ply 
    #../eulernjf_data/nonhuman/triceratop/triceratop_deer.ply 
    ../eulernjf_data/nonhuman/triceratop/triceratop_dog.ply 
    #../eulernjf_data/nonhuman/bunny/bunny.ply 
    #../eulernjf_data/nonhuman/jared/jared_v1.ply 
    #../eulernjf_data/nonhuman/horse/horse.ply 
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.ply 
    #../eulernjf_data/nonhuman/cyclops/cyclops.ply 
    #../eulernjf_data/nonhuman/octoman/octoman.ply 
    #../eulernjf_data/nonhuman/holey/holey_man.ply 
  nonhuman_features:
    #../eulernjf_data/nonhuman/wolf/wolf_d4d_deer.npy
    #../eulernjf_data/nonhuman/wolf/wolf_d4d_dog.npy
    #../eulernjf_data/nonhuman/wolf/wolf_bear.npy
    #../eulernjf_data/nonhuman/triceratop/triceratop_bear.npy
    #../eulernjf_data/nonhuman/triceratop/triceratop_deer.npy
    ../eulernjf_data/nonhuman/triceratop/triceratop_dog.npy
    #../eulernjf_data/nonhuman/bunny/bunny.npy
    #../eulernjf_data/nonhuman/jared/jared_v1.npy
    #../eulernjf_data/nonhuman/horse/horse.npy
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.npy
    #../eulernjf_data/nonhuman/cyclops/cyclops.npy
    #../eulernjf_data/nonhuman/octoman/octoman.npy
    #../eulernjf_data/nonhuman/holey/holey_man.npy
  objroot: ../eulernjf_data/running_on_spot_dino/
  src_names: ["doggie_jumprun"] #"50026"] #"50027"] #"50004","50007","50009","50022","50026","50027"]
  tgt_names: ["doggie_jumprun"] #"50021"] #"50004"]
  result_dir: "../sig24/jumprun/triceratop/"
  stepsize: 0.05
  method: "eulernjf"