datadir:
  ../eulernjf_data/animals/train_1/
bodymodel: "../body_models/"
training:
  batch: 1 
  epochs: 2000
  lr: 1e-3
  expt: "njfode"
  code_size: 16 
  encoding: "joints"
data:
  seq_length: 32
  max_frames: 10000
  feature_dir: ../eulernjf_data/wks/
weight:
  directory : "../models/"
  path: "../models/ode_animals_pointfeat_wks_split_1"
  pose: "../models/posing_running_pointfeat_all_dmpl" 
logging:
  directory : "../logs/secondary_animals_pointfeat_wks_split_1_b01/"
test:
  test: True 
  datadir:
    ../eulernjf_data/animals/train_1/
    #../eulernjf_data/subject_50027_run/train/
  dataset_meshdir:
    ../eulernjf_data/first_frames/
  motion_name:
    "jumping_jacks"
  mode:
    "nonhuman"
  nonhuman_mesh:
    #../eulernjf_data/nonhuman/wolf/wolf_dog0.ply 
    ../eulernjf_data/nonhuman/triceratop/triceratop_dog0.ply 
    #../eulernjf_data/nonhuman/triceratop/triceratop.ply 
    #../eulernjf_data/nonhuman/jared/jared_v1.ply 
    #../eulernjf_data/nonhuman/horse/horse.ply 
    #../eulernjf_data/nonhuman/reptile/reptile_dog0.ply 
  nonhuman_features:
    #../eulernjf_data/nonhuman/wolf/wolf_dog0.npy
    ../eulernjf_data/nonhuman/triceratop/triceratop_dog0.npy
    #../eulernjf_data/nonhuman/triceratop/triceratop.npy
    #../eulernjf_data/nonhuman/bunny/bunny.npy
    #../eulernjf_data/nonhuman/jared/jared_v1.npy
    #../eulernjf_data/nonhuman/horse/horse.npy
    #../eulernjf_data/nonhuman/reptile/reptile_dog0.npy
  objroot: ../eulernjf_data/running_on_spot_dino/
  src_names: ["dog0"] #"50026"] #"50027"] #"50004","50007","50009","50022","50026","50027"]
  tgt_names: ["dog0"] #"50021"] #"50004"]
  result_dir: "../sig24/dogmotion/triceratop/"
  stepsize: 0.05
  method: "eulernjf"