datadir:
  ../eulernjf_data/jumping_jacks/test_2/
bodymodel: "../body_models/"
training:
  batch: 1 
  epochs: 200 
  lr: 1e-3
  expt: "njfode"
  code_size: 16 
  encoding: "joints"
  aug_dim: 0
data:
  seq_length: 32 
  max_frames: 10000
  feature_dir: ../eulernjf_data/wks/
weight:
  directory : "../models_trj/jumping/"
  #path: "../models/ode_jj_pointfeat_wks_split_1_b01"
  path: "../models_trj/jumping/jumping_trj"
  pose: "../models/posing_jj_pointfeat_all_dmpl" 
logging:
  directory : "../logs/jumping_trj/"
test:
  test: True 
  datadir:
    ../eulernjf_data/jumping_jacks/train_5/
  dataset_meshdir:
    ../eulernjf_data/first_frames/
  motion_name:
    "jumping_jacks"
  mode:
    "human"
  nonhuman_mesh:
    #../eulernjf_data/nonhuman/bunny/bunny.ply 
    #../eulernjf_data/nonhuman/jared/jared_v1.ply 
    #../eulernjf_data/nonhuman/horse/horse.ply 
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.ply 
    #../eulernjf_data/nonhuman/cyclops/cyclops.ply 
    #../eulernjf_data/nonhuman/octoman/octoman.ply 
    #../eulernjf_data/nonhuman/prisoner/prisoner.ply 
    #../eulernjf_data/nonhuman/mousey/mousey_meshlab.ply 
    #../eulernjf_data/nonhuman/warrok/warrok_meshlab.ply 
    #../eulernjf_data/nonhuman/faust/scan.ply 
    #../eulernjf_data/nonhuman/skeletonzombie/skeletonzombie_rot90.ply
    ../eulernjf_data/nonhuman/maynard/maynard_rot90.ply
    #../eulernjf_data/nonhuman/holey/holey_man_rot90.ply 
  nonhuman_features:
    #../eulernjf_data/nonhuman/bunny/bunny.npy
    #../eulernjf_data/nonhuman/jared/jared_v1.npy
    #../eulernjf_data/nonhuman/horse/horse.npy
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.npy
    #../eulernjf_data/nonhuman/cyclops/cyclops.npy
    #../eulernjf_data/nonhuman/octoman/octoman.npy
    #../eulernjf_data/nonhuman/prisoner/prisoner.npy
    #../eulernjf_data/nonhuman/holey/holey_man.npy
    #../eulernjf_data/nonhuman/skeletonzombie/skeletonzombie_rot90.npy
    ../eulernjf_data/nonhuman/maynard/maynard_rot90.npy
    #../eulernjf_data/nonhuman/holey/holey_man_rot90.npy
    #../eulernjf_data/nonhuman/mousey/mousey_meshlab.npy
    #../eulernjf_data/nonhuman/warrok/warrok_meshlab.npy
    #../eulernjf_data/nonhuman/faust/scan.npy
  objroot: ../eulernjf_data/running_on_spot_dino/
  src_names: ["50007","50027"] #"50007"] #"50026"] #"50027"] #"50004","50007","50009","50022","50026","50027"]
  tgt_names: ["50002"] #"50007","50002","50022"]  #"50021"] #"50004"]
  result_dir: "../Siggraph_Asia/jumping/unseen/"
  stepsize: 0.05
  method: "trj"