datadir:
  ../eulernjf_data/punching/test_3/
bodymodel: "../body_models/"
training:
  batch: 1 
  epochs: 150 
  lr: 1e-3
  expt: "njfode"
  code_size: 16 
  encoding: "joints"
  aug_dim: 0
data:
  seq_length: 32 
  max_frames: 10000
  feature_dir: ../eulernjf_data/wks/
weight:
  directory : "../models_trj/punching/"
  #path: "../models/ode_punching_pointfeat_wks_split_1_b01"
  path: "../models_trj/punching/punching_trj"
  pose: "../models/posing_running_pointfeat_all_dmpl" 
logging:
  directory : "../logs/punching_trj/"
test:
  test: True 
  sig: False 
  datadir:
    ../eulernjf_data/punching/train_7/
    #../eulernjf_data/subject_50027_run/train/
  dataset_meshdir:
    ../eulernjf_data/first_frames/
  motion_name:
    "punching"
  mode:
    "human"
  nonhuman_mesh:
    #../eulernjf_data/nonhuman/cyclops/cyclops.ply 
    #../eulernjf_data/nonhuman/greenmonster/green_monster.ply 
    #../eulernjf_data/nonhuman/holey/holey_man.ply 
    #../eulernjf_data/nonhuman/maynard/maynard.ply 
    #../eulernjf_data/nonhuman/jared/jared_v1.ply 
    #../eulernjf_data/nonhuman/bunny/bunny.ply 
    #../eulernjf_data/nonhuman/warrok/warrok_meshlab.ply 
    #../eulernjf_data/nonhuman/skeletonzombie/skeletonzombie_meshlab.ply 
    #../eulernjf_data/nonhuman/mousey/mousey_meshlab.ply 
    #../eulernjf_data/nonhuman/faust/scan.ply 
    #../eulernjf_data/nonhuman/horse/horse.ply 
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.ply 
    ../eulernjf_data/nonhuman/bunny/bunny_rot90.ply 
    #../eulernjf_data/nonhuman/faust/scan_rot90.ply 
    #../eulernjf_data/nonhuman/maynard/maynard_rot90.ply 
  nonhuman_features:
    #../eulernjf_data/nonhuman/cyclops/cyclops.npy
    #../eulernjf_data/nonhuman/greenmonster/green_monster.npy
    #../eulernjf_data/nonhuman/holey/holey_man.npy
    #../eulernjf_data/nonhuman/maynard/maynard.npy
    #../eulernjf_data/nonhuman/jared/jared_v1.npy
    #../eulernjf_data/nonhuman/warrok/warrok_meshlab.npy
    #../eulernjf_data/nonhuman/faust/scan.npy
    #../eulernjf_data/nonhuman/skeletonzombie/skeletonzombie_meshlab.npy
    ../eulernjf_data/nonhuman/bunny/bunny_rot90.npy
    #../eulernjf_data/nonhuman/mousey/mousey_meshlab.npy
    #../eulernjf_data/nonhuman/faust/scan_rot90.npy
    #../eulernjf_data/nonhuman/maynard/maynard_rot90.npy
    #../eulernjf_data/nonhuman/horse/horse.npy
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.npy
  objroot: ../eulernjf_data/running_on_spot_dino/
  src_names: ["50027","50007","50026"] #"50026"] #"50027"] #"50004","50007","50009","50022","50026","50027"]
  tgt_names: ["50002"] #"50004","50009","50020","50021","50022"] #"50021"] #"50004"]
  result_dir: "../Siggraph_Asia/punching/unseen/"
  stepsize: 0.05
  method: "trj"