datadir:
  ../eulernjf_data/running_on_spot/test_3/
bodymodel: "../body_models/"
training:
  batch: 1 
  epochs: 100 
  lr: 1e-3
  expt: "njfode"
  code_size: 16 
  encoding: "joints"
  aug_dim: 0 
data:
  seq_length: 32 
  max_frames: 10000
  feature_dir: ../eulernjf_data/wks/
weight:
  directory : "../models_trj/running/"
  #path: "../models/ode_running_pointfeat_wks_split_1_b01_eccv"
  path: "../models_trj/running/running_trj"
  #path: "../models/augode_running_weightedjac_aug32_woproj"
  #path: "../models/augode_running_weightedjac_aug64_woproj"
  #path: "../models/running_ours_pose_centroids"
  #path: "../models/augode_running_weightedjac_aug32_noadj" #not adjoint method
  pose: "../models/posing_running_pointfeat" 
logging:
  #directory : "../logs/secondary_running_pointfeat_wks_split_1_b01_siga_cnwks/"
  #directory : "../logs/augode_running_weightedjac_aug32_woproj/"
  #directory : "../logs/augode_running_weightedjac_aug64_woproj/"
  directory : "../logs/running_trj/"
  #directory : "../logs/augode_running_weightedjac_aug32_noadj/" #not adjoint method
  #directory : "../logs/augode_running_weightedjac/" #weighted-jac aug-ode
test:
  test: True 
  datadir:
    ../eulernjf_data/running_on_spot/train_7/
    #../eulernjf_data/subject_50027_run/train/
  dataset_meshdir:
    ../eulernjf_data/first_frames/
  motion_name:
    "jumping_jacks"
  mode:
    "human"
  sig:
    False 
  nonhuman_mesh:
    #../eulernjf_data/nonhuman/bunny/bunny.ply 
    #../eulernjf_data/nonhuman/greenmonster/green_monster_rot90.ply 
    #../eulernjf_data/nonhuman/faust/scan.ply 
    #../eulernjf_data/nonhuman/warrok/warrok_meshlab.ply 
    #../eulernjf_data/nonhuman/mousey/mousey_meshlab.ply 
    #../eulernjf_data/nonhuman/prisoner/prisoner.ply 
    #../eulernjf_data/nonhuman/maynard/maynard.ply 
    #../eulernjf_data/nonhuman/holey/holey_man_rot90.ply 
    #../eulernjf_data/nonhuman/jared/jared_rot90.ply 
    #../eulernjf_data/nonhuman/horse/horse.ply 
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.ply 
    #../eulernjf_data/nonhuman/octoman/octoman.ply 
  nonhuman_features:
    #../eulernjf_data/nonhuman/bunny/bunny.npy
    #../eulernjf_data/nonhuman/greenmonster/green_monster_rot90.npy
    #../eulernjf_data/nonhuman/faust/scan.npy
    #../eulernjf_data/nonhuman/warrok/warrok_meshlab.npy
    #../eulernjf_data/nonhuman/prisoner/prisoner.npy
    #../eulernjf_data/nonhuman/maynard/maynard.npy
    #../eulernjf_data/nonhuman/mousey/mousey_meshlab.npy
    #../eulernjf_data/nonhuman/holey/holey_man_rot90.npy
    ../eulernjf_data/nonhuman/jared/jared_rot90.npy
    #../eulernjf_data/nonhuman/horse/horse.npy
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.npy
    #../eulernjf_data/nonhuman/octoman/octoman.npy
  objroot: ../eulernjf_data/running_on_spot_dino/
  src_names: ["50026","50021","50027"] #"50021","50026"] #"50026"] #"50027"] #"50004","50007","50009","50022","50026","50027"]
  tgt_names: ["50002"] #,"50007","50026","50022","50020"]
  result_dir: "../Siggraph_Asia/running/unseen/"
  stepsize: 0.0
  method: "trj"
  #method: "augode_eulernjf_fulljac_aug64_woproj"