datadir:
  ../eulernjf_data/running_on_spot/train/
  #../eulernjf_data/subject_50002_50027_run/train/
bodymodel: "../body_models/"
training:
  batch: 1 
  epochs: 2000
  lr: 1e-4
  expt: "njfode"
  code_size: 16 
  encoding: "joints"
data:
  seq_length: 32 
  max_frames: 10000
weight:
  directory : "../models/"
  #path: "../models/ode_running_pointfeat_with_previous_attn"
  path: "../models/ode_running_pointfeat"
  pose: "../models/posing_running_pointfeat_all_dmpl" 
logging:
  #directory : "../logs/secondary_running_pointfeat_with_previous_attn_eval/"
  directory : "../logs/secondary_running_pointfeat_eval/"
test:
  test: True 
  datadir:
    ../eulernjf_data/subject_50027_run/train/
  dataset_meshdir:
    ../eulernjf_data/first_frames/
  motion_name:
    "jumping_jacks"
  mode:
    "nonhuman"
  nonhuman_mesh:
    #../eulernjf_data/nonhuman/bunny/bunny.ply 
    #../eulernjf_data/nonhuman/jared/jared_v1.ply
    #../eulernjf_data/nonhuman/holey/holey_man.ply
    #../eulernjf_data/nonhuman/greenmonster/green_monster.ply
    ../eulernjf_data/nonhuman/reptile/reptile_meshlab.ply
    #../eulernjf_data/nonhuman/octoman/octoman.ply
    #../eulernjf_data/nonhuman/cyclops/cyclops.ply
  nonhuman_features:
    ../eulernjf_data/nonhuman/bunny/bunny.npy
  objroot: ../eulernjf_data/running_on_spot_dino/
  src_names: ["50027"] #"50027"] #"50004","50007","50009","50022","50026","50027"]
  tgt_names: ["50027"] #"50021"] #"50004"]
  result_dir: "../sig24_results/running_reptile/"
  stepsize: 0.05
  method: "eulernjf"