datadir:
  ../eulernjf_data/running_on_spot/train_1/
  #../eulernjf_data/subject_50002_50027_run/train/
bodymodel: "../body_models/"
training:
  batch: 1 
  epochs: 2000
  lr: 1e-3
  expt: "njfode"
  code_size: 16 
  encoding: "joints"
data:
  seq_length: 32 
  max_frames: 10000
  feature_dir: ../eulernjf_data/wks/
weight:
  directory : "../models/"
  #path: "../models/ode_running_pointfeat_wks_split_1_b01"
  path: "../models/ode_running_pointfeat_wks_split_1_wsig"
  pose: "../models/posing_running_pointfeat_all_dmpl" 
logging:
  directory : "../logs/secondary_running_pointfeat_wks_split_1_wsig/"
test:
  test: False 
  datadir:
    ../eulernjf_data/running_on_spot/train_1/
    #../eulernjf_data/subject_50027_run/train/
  dataset_meshdir:
    ../eulernjf_data/first_frames/
  motion_name:
    "jumping_jacks"
  mode:
    "human"
  sig:
    False 
  nonhuman_mesh:
    #../eulernjf_data/nonhuman/bunny/bunny.ply 
    #../eulernjf_data/nonhuman/greenmonster/green_monster.ply 
    #../eulernjf_data/nonhuman/faust/scan.ply 
    #../eulernjf_data/nonhuman/warrok/warrok_meshlab.ply 
    #../eulernjf_data/nonhuman/mousey/mousey_meshlab.ply 
    #../eulernjf_data/nonhuman/prisoner/prisoner.ply 
    #../eulernjf_data/nonhuman/maynard/maynard.ply 
    #../eulernjf_data/nonhuman/holey/holey_man.ply 
    #../eulernjf_data/nonhuman/jared/jared_v1.ply 
    #../eulernjf_data/nonhuman/horse/horse.ply 
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.ply 
    ../eulernjf_data/nonhuman/octoman/octoman.ply 
  nonhuman_features:
    #../eulernjf_data/nonhuman/bunny/bunny.npy
    #../eulernjf_data/nonhuman/greenmonster/green_monster.npy
    #../eulernjf_data/nonhuman/faust/scan.npy
    #../eulernjf_data/nonhuman/warrok/warrok_meshlab.npy
    #../eulernjf_data/nonhuman/prisoner/prisoner.npy
    #../eulernjf_data/nonhuman/maynard/maynard.npy
    #../eulernjf_data/nonhuman/mousey/mousey_meshlab.npy
    #../eulernjf_data/nonhuman/holey/holey_man.npy
    #../eulernjf_data/nonhuman/jared/jared_v1.npy
    #../eulernjf_data/nonhuman/horse/horse.npy
    #../eulernjf_data/nonhuman/reptile/reptile_meshlab.npy
    ../eulernjf_data/nonhuman/octoman/octoman.npy
  objroot: ../eulernjf_data/running_on_spot_dino/
  src_names: ["50009"] #"50026"] #"50027"] #"50004","50007","50009","50022","50026","50027"]
  tgt_names: ["50004","50007","50002","50020","500022","50026"] #"50021"] #"50004"]
  result_dir: "../sig24/running/temp_ours/"
  stepsize: 0.05
  method: "eulernjf"